In [10]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
# Load dataset

df = pd.read_csv(
    r"C:\Users\deore\Downloads\archive (2)\books.csv",
    on_bad_lines="skip"
)

In [12]:
# inspect the dataset

df.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

In [13]:
df.shape

(11123, 12)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11123 entries, 0 to 11122
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   bookID              11123 non-null  int64
 1   title               11123 non-null  object
 2   authors             11123 non-null  object
 3   average_rating      11123 non-null  float64
 4   isbn                11123 non-null  object
 5   isbn13              11123 non-null  int64
 6   language_code       11123 non-null  object
 7     num_pages         11123 non-null  int64
 8   ratings_count       11123 non-null  int64
 9   text_reviews_count  11123 non-null  int64
 10  publication_date    11123 non-null  object
 11  publisher           11123 non-null  object
dtypes: float64(1), int64(5), object(6)
memory usage: 1.0+ MB

In [15]:
df.describe()

,bookID,average_rating,isbn13,num_pages,ratings_count,text_reviews_count
count,11123.000000,11123.000000,1.112300e+04,11123.000000,1.112300e+04,11123.000000
mean,21310.856963,3.934075,9.759880e+12,336.405556,1.794285e+04,542.048099
std,13094.727252,0.350485,4.429758e+11,241.152626,1.124992e+05,2576.619589
min,1.000000,0.000000,8.987060e+09,0.000000,0.000000e+00,0.000000
25%,10277.500000,3.770000,9.780345e+12,192.000000,1.040000e+02,9.000000
50%,20287.000000,3.960000,9.780582e+12,299.000000,7.450000e+02,47.000000
75%,32104.500000,4.140000,9.780872e+12,416.000000,5.000500e+03,238.000000
max,45641.000000,5.000000,9.790008e+12,6576.000000,4.597666e+06,94265.000000

In [16]:
df.columns

Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', '  num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher'],
      dtype='object')

In [18]:
# clean column names 

df.columns = df.columns.str.strip()
df.columns

Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', 'num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher'],
      dtype='object')

In [19]:
# check missing values

df.isnull().sum(

bookID                0
title                 0
authors               0
average_rating        0
isbn                  0
isbn13                0
language_code         0
num_pages             0
ratings_count         0
text_reviews_count    0
publication_date      0
publisher             0
dtype: int64

In [21]:
# check missing values percentage in each column
(df.isnull().sum() / len(df) * 100).round(2)

bookID                0.0
title                 0.0
authors               0.0
average_rating        0.0
isbn                  0.0
isbn13                0.0
language_code         0.0
num_pages             0.0
ratings_count         0.0
text_reviews_count    0.0
publication_date      0.0
publisher             0.0
dtype: float64

# remove duplicate records

In [22]:
# count duplicates
df.duplicated().sum()

np.int64(0)

# title column

In [24]:
# count duplicate title in dataset
df["title"].duplicated().sum()

np.int64(775)

In [26]:
# print rows of duplicate title
df.loc[df["title"].duplicated(), "title"]

10       The Hitchhiker's Guide to the Galaxy (Hitchhik...
24       The Lord of the Rings (The Lord of the Rings  ...
37                                          The Changeling
40                                         The Known World
41                                         The Known World
                               ...
11075            Encuentro en el Ártico (Artemis Fowl  #2)
11076                      Artemis Fowl (Artemis Fowl  #1)
11078            The Subtle Knife (His Dark Materials  #2)
11080            The Subtle Knife (His Dark Materials  #2)
11096                                          On the Road
Name: title, Length: 775, dtype: object

In [27]:
#  see all duplicate titles
df[df["title"].duplicated(keep=False)]

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
9,14,The Hitchhiker's Guide to the Galaxy (Hitchhik...,Douglas Adams,4.22,1400052920,9781400052929,eng,215,4930,460,8/3/2004,Crown
10,16,The Hitchhiker's Guide to the Galaxy (Hitchhik...,Douglas Adams/Stephen Fry,4.22,0739322206,9780739322208,eng,6,1266,253,3/23/2005,Random House Audio
...,...,...,...,...,...,...,...,...,...,...,...,...
11075,45463,Encuentro en el Ártico (Artemis Fowl #2),Eoin Colfer/Ana Alcaina Pérez,3.95,0307343103,9780307343109,spa,320,15,3,7/5/2005,Montena
11076,45465,Artemis Fowl (Artemis Fowl #1),Eoin Colfer/Nathaniel Parker,3.84,1400085918,9781400085910,eng,6,55,14,4/6/2004,Listening Library
11078,45479,The Subtle Knife (His Dark Materials #2),Philip Pullman/Ian Beck,4.13,0375846727,9780375846724,eng,326,677,77,9/1/2007,Alfred A. Knopf Books for Young Readers
11080,45485,The Subtle Knife (His Dark Materials #2),Philip Pullman,4.13,0807210471,9780807210475,eng,8,39,8,1/28/2000,Listening Library
11096,45536,On the Road,Jack Kerouac/Ann Charters,3.63,0142437255,9780142437254,en-US,307,3271,342,1/3/2006,Penguin Classics

In [28]:
# remove duplicate rows and keep first
df = df.drop_duplicates("title",keep="first")

In [29]:
# check duplicates
df["title"].duplicated().sum()

np.int64(0)

In [30]:
# find the type of the title colum
df["title"].dtypes

dtype('O')

# authors column

In [32]:
# find type of author
df['authors'].dtypes

dtype('O')

In [34]:

df['authors'].isna().sum()

np.int64(0)

# rating column

In [37]:
# find type of rating 
df["average_rating"].dtypes

dtype('float64')

In [38]:
# check null values
df["average_rating"].isna().sum()

np.int64(0)

In [49]:
# check invalid ratings
i=df[
    (df["average_rating"] < 0) |
    (df["average_rating"] > 5)
]

i

Empty DataFrame
Columns: [bookID, title, authors, average_rating, isbn, isbn13, language_code, num_pages, ratings_count, text_reviews_count, publication_date, publisher]
Index: []

In [50]:
# find the min and max of the average_rating column
df["average_rating"].min(), df["average_rating"].max()

(0.0, 5.0)

# Publication date

In [51]:
# check the type of publication_date
df["publication_date"].dtypes

dtype('O')

In [56]:
# find the missing values
df["publication_date"].isna().sum()

np.int64(0)

In [58]:
df = df.copy()

In [59]:
# convert object to datetime format
df["publication_date"] = pd.to_datetime(
    df["publication_date"],
    errors = "coerce")

In [60]:
# create a separate year column
df["publication_year"] = df["publication_date"].dt.year

In [61]:
# check both columns
df[["publication_date","publication_year"]].head()

  publication_date  publication_year
0       2006-09-16            2006.0
1       2004-09-01            2004.0
2       2003-11-01            2003.0
3       2004-05-01            2004.0
4       2004-09-13            2004.0

In [62]:
# check type of publication_year
df["publication_year"].dtypes

dtype('float64')

In [65]:
# convert float to int
df["publication_year"]=df["publication_year"].astype("Int64")

In [68]:
# check the type
df["publication_year"].dtypes

Int64Dtype()

In [70]:
df["publication_year"].isnull().sum()

np.int64(2)

In [71]:
df = df.dropna(subset=["publication_year"])

In [72]:
df["publication_year"].dtypes

Int64Dtype()

In [73]:
df["publication_year"].isnull().sum()

np.int64(0)